# permissions to do viewer nextclouds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nextcloud-viewer-role
rules:
- apiGroups:
  - apps.libre.sh
  resources:
  - nextclouds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.libre.sh
  resources:
  - nextclouds/status
  verbs:
  - get
