// +build !ignore_autogenerated

/*

Licensed under the GNU AFFERO GENERAL PUBLIC LICENSE Version 3 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.gnu.org/licenses/agpl-3.0.html

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.libre.sh/controller-utils/application/components"
	"k8s.libre.sh/controller-utils/application/settings"
	"k8s.libre.sh/controller-utils/application/settings/parameters"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *App) DeepCopyInto(out *App) {
	*out = *in
	if in.InternalWorkload != nil {
		in, out := &in.InternalWorkload, &out.InternalWorkload
		*out = new(components.InternalWorkload)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new App.
func (in *App) DeepCopy() *App {
	if in == nil {
		return nil
	}
	out := new(App)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSettings.
func (in *AppSettings) DeepCopy() *AppSettings {
	if in == nil {
		return nil
	}
	out := new(AppSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppStore) DeepCopyInto(out *AppStore) {
	*out = *in
	if in.StoreEnabled != nil {
		in, out := &in.StoreEnabled, &out.StoreEnabled
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.StoreURL != nil {
		in, out := &in.StoreURL, &out.StoreURL
		*out = new(parameters.Parameter)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppStore.
func (in *AppStore) DeepCopy() *AppStore {
	if in == nil {
		return nil
	}
	out := new(AppStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJob) DeepCopyInto(out *CronJob) {
	*out = *in
	if in.CronJob != nil {
		in, out := &in.CronJob, &out.CronJob
		*out = new(components.CronJob)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJob.
func (in *CronJob) DeepCopy() *CronJob {
	if in == nil {
		return nil
	}
	out := new(CronJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Database) DeepCopyInto(out *Database) {
	*out = *in
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(parameters.Parameter)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Database.
func (in *Database) DeepCopy() *Database {
	if in == nil {
		return nil
	}
	out := new(Database)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *General) DeepCopyInto(out *General) {
	*out = *in
	in.AppStore.DeepCopyInto(&out.AppStore)
	in.Locales.DeepCopyInto(&out.Locales)
	in.GlobalSecrets.DeepCopyInto(&out.GlobalSecrets)
	in.GlobalSettings.DeepCopyInto(&out.GlobalSettings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new General.
func (in *General) DeepCopy() *General {
	if in == nil {
		return nil
	}
	out := new(General)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSecrets) DeepCopyInto(out *GlobalSecrets) {
	*out = *in
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.PasswordSalt != nil {
		in, out := &in.PasswordSalt, &out.PasswordSalt
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.AdminPassword != nil {
		in, out := &in.AdminPassword, &out.AdminPassword
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.AdminUsername != nil {
		in, out := &in.AdminUsername, &out.AdminUsername
		*out = new(parameters.Parameter)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSecrets.
func (in *GlobalSecrets) DeepCopy() *GlobalSecrets {
	if in == nil {
		return nil
	}
	out := new(GlobalSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSettings) DeepCopyInto(out *GlobalSettings) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.OverwriteCLI != nil {
		in, out := &in.OverwriteCLI, &out.OverwriteCLI
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.OverwriteProtocol != nil {
		in, out := &in.OverwriteProtocol, &out.OverwriteProtocol
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.DataDirectory != nil {
		in, out := &in.DataDirectory, &out.DataDirectory
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.UpdateChecker != nil {
		in, out := &in.UpdateChecker, &out.UpdateChecker
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.UpdateURL != nil {
		in, out := &in.UpdateURL, &out.UpdateURL
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.UpdateChannel != nil {
		in, out := &in.UpdateChannel, &out.UpdateChannel
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.UpdateDisable != nil {
		in, out := &in.UpdateDisable, &out.UpdateDisable
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.BruteForce != nil {
		in, out := &in.BruteForce, &out.BruteForce
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(parameters.Parameter)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSettings.
func (in *GlobalSettings) DeepCopy() *GlobalSettings {
	if in == nil {
		return nil
	}
	out := new(GlobalSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Jobs) DeepCopyInto(out *Jobs) {
	*out = *in
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = new(components.Jobs)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Jobs.
func (in *Jobs) DeepCopy() *Jobs {
	if in == nil {
		return nil
	}
	out := new(Jobs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Locales) DeepCopyInto(out *Locales) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Locale != nil {
		in, out := &in.Locale, &out.Locale
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.ForceLanguage != nil {
		in, out := &in.ForceLanguage, &out.ForceLanguage
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.ForceLocale != nil {
		in, out := &in.ForceLocale, &out.ForceLocale
		*out = new(parameters.Parameter)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Locales.
func (in *Locales) DeepCopy() *Locales {
	if in == nil {
		return nil
	}
	out := new(Locales)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nextcloud) DeepCopyInto(out *Nextcloud) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nextcloud.
func (in *Nextcloud) DeepCopy() *Nextcloud {
	if in == nil {
		return nil
	}
	out := new(Nextcloud)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Nextcloud) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextcloudList) DeepCopyInto(out *NextcloudList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Nextcloud, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextcloudList.
func (in *NextcloudList) DeepCopy() *NextcloudList {
	if in == nil {
		return nil
	}
	out := new(NextcloudList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NextcloudList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextcloudSpec) DeepCopyInto(out *NextcloudSpec) {
	*out = *in
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(Settings)
		(*in).DeepCopyInto(*out)
	}
	if in.App != nil {
		in, out := &in.App, &out.App
		*out = new(App)
		(*in).DeepCopyInto(*out)
	}
	if in.Web != nil {
		in, out := &in.Web, &out.Web
		*out = new(Web)
		(*in).DeepCopyInto(*out)
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = new(Jobs)
		(*in).DeepCopyInto(*out)
	}
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(CronJob)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextcloudSpec.
func (in *NextcloudSpec) DeepCopy() *NextcloudSpec {
	if in == nil {
		return nil
	}
	out := new(NextcloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextcloudStatus) DeepCopyInto(out *NextcloudStatus) {
	*out = *in
	in.ApplicationStatus.DeepCopyInto(&out.ApplicationStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextcloudStatus.
func (in *NextcloudStatus) DeepCopy() *NextcloudStatus {
	if in == nil {
		return nil
	}
	out := new(NextcloudStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStore) DeepCopyInto(out *ObjectStore) {
	*out = *in
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.AutoCreate != nil {
		in, out := &in.AutoCreate, &out.AutoCreate
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.PathStyle != nil {
		in, out := &in.PathStyle, &out.PathStyle
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.AccessKeyID != nil {
		in, out := &in.AccessKeyID, &out.AccessKeyID
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.SecretAccessKey != nil {
		in, out := &in.SecretAccessKey, &out.SecretAccessKey
		*out = new(parameters.Parameter)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStore.
func (in *ObjectStore) DeepCopy() *ObjectStore {
	if in == nil {
		return nil
	}
	out := new(ObjectStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Redis) DeepCopyInto(out *Redis) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(parameters.Parameter)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Redis.
func (in *Redis) DeepCopy() *Redis {
	if in == nil {
		return nil
	}
	out := new(Redis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMTP) DeepCopyInto(out *SMTP) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.FromAdress != nil {
		in, out := &in.FromAdress, &out.FromAdress
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Secure != nil {
		in, out := &in.Secure, &out.Secure
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.AuthType != nil {
		in, out := &in.AuthType, &out.AuthType
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.TemplateClass != nil {
		in, out := &in.TemplateClass, &out.TemplateClass
		*out = new(parameters.Parameter)
		**out = **in
	}
	if in.PlainTextOnly != nil {
		in, out := &in.PlainTextOnly, &out.PlainTextOnly
		*out = new(parameters.Parameter)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMTP.
func (in *SMTP) DeepCopy() *SMTP {
	if in == nil {
		return nil
	}
	out := new(SMTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Settings) DeepCopyInto(out *Settings) {
	*out = *in
	if in.CreateOptions != nil {
		in, out := &in.CreateOptions, &out.CreateOptions
		*out = new(settings.CreateOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]*settings.Source, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(settings.Source)
				**out = **in
			}
		}
	}
	if in.AppSettings != nil {
		in, out := &in.AppSettings, &out.AppSettings
		*out = (*in).DeepCopy()
	}
	if in.Web != nil {
		in, out := &in.Web, &out.Web
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Settings.
func (in *Settings) DeepCopy() *Settings {
	if in == nil {
		return nil
	}
	out := new(Settings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Web) DeepCopyInto(out *Web) {
	*out = *in
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(components.Workload)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Web.
func (in *Web) DeepCopy() *Web {
	if in == nil {
		return nil
	}
	out := new(Web)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebSettings.
func (in *WebSettings) DeepCopy() *WebSettings {
	if in == nil {
		return nil
	}
	out := new(WebSettings)
	in.DeepCopyInto(out)
	return out
}
