// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.libre.sh/application/settings"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSecrets) DeepCopyInto(out *AppSecrets) {
	*out = *in
	out.InstanceID = in.InstanceID
	out.PasswordSalt = in.PasswordSalt
	out.Secret = in.Secret
	out.AdminPassword = in.AdminPassword
	out.AdminUsername = in.AdminUsername
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSecrets.
func (in *AppSecrets) DeepCopy() *AppSecrets {
	if in == nil {
		return nil
	}
	out := new(AppSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSettings) DeepCopyInto(out *AppSettings) {
	*out = *in
	out.OverwriteCLI = in.OverwriteCLI
	out.OverwriteProtocol = in.OverwriteProtocol
	out.DataDirectory = in.DataDirectory
	out.Debug = in.Debug
	out.ReadOnly = in.ReadOnly
	out.UpdateChecker = in.UpdateChecker
	out.UpdateURL = in.UpdateURL
	out.UpdateChannel = in.UpdateChannel
	out.UpdateDisable = in.UpdateDisable
	out.BruteForce = in.BruteForce
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSettings.
func (in *AppSettings) DeepCopy() *AppSettings {
	if in == nil {
		return nil
	}
	out := new(AppSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppStore) DeepCopyInto(out *AppStore) {
	*out = *in
	out.StoreEnabled = in.StoreEnabled
	out.Default = in.Default
	out.StoreURL = in.StoreURL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppStore.
func (in *AppStore) DeepCopy() *AppStore {
	if in == nil {
		return nil
	}
	out := new(AppStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Database) DeepCopyInto(out *Database) {
	*out = *in
	out.Database = in.Database
	out.Host = in.Host
	out.Port = in.Port
	out.Type = in.Type
	out.Username = in.Username
	out.Password = in.Password
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Database.
func (in *Database) DeepCopy() *Database {
	if in == nil {
		return nil
	}
	out := new(Database)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *General) DeepCopyInto(out *General) {
	*out = *in
	out.AppStore = in.AppStore
	out.Locales = in.Locales
	out.AppSecrets = in.AppSecrets
	out.AppSettings = in.AppSettings
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new General.
func (in *General) DeepCopy() *General {
	if in == nil {
		return nil
	}
	out := new(General)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Locales) DeepCopyInto(out *Locales) {
	*out = *in
	out.Default = in.Default
	out.Locale = in.Locale
	out.ForceLanguage = in.ForceLanguage
	out.ForceLocale = in.ForceLocale
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Locales.
func (in *Locales) DeepCopy() *Locales {
	if in == nil {
		return nil
	}
	out := new(Locales)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nextcloud) DeepCopyInto(out *Nextcloud) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nextcloud.
func (in *Nextcloud) DeepCopy() *Nextcloud {
	if in == nil {
		return nil
	}
	out := new(Nextcloud)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Nextcloud) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextcloudList) DeepCopyInto(out *NextcloudList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Nextcloud, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextcloudList.
func (in *NextcloudList) DeepCopy() *NextcloudList {
	if in == nil {
		return nil
	}
	out := new(NextcloudList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NextcloudList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextcloudSpec) DeepCopyInto(out *NextcloudSpec) {
	*out = *in
	in.Settings.DeepCopyInto(&out.Settings)
	in.App.DeepCopyInto(&out.App)
	in.Web.DeepCopyInto(&out.Web)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextcloudSpec.
func (in *NextcloudSpec) DeepCopy() *NextcloudSpec {
	if in == nil {
		return nil
	}
	out := new(NextcloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextcloudStatus) DeepCopyInto(out *NextcloudStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextcloudStatus.
func (in *NextcloudStatus) DeepCopy() *NextcloudStatus {
	if in == nil {
		return nil
	}
	out := new(NextcloudStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStore) DeepCopyInto(out *ObjectStore) {
	*out = *in
	out.Bucket = in.Bucket
	out.Host = in.Host
	out.Port = in.Port
	out.AutoCreate = in.AutoCreate
	out.SSL = in.SSL
	out.Region = in.Region
	out.PathStyle = in.PathStyle
	out.AccessKeyID = in.AccessKeyID
	out.SecretAccessKey = in.SecretAccessKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStore.
func (in *ObjectStore) DeepCopy() *ObjectStore {
	if in == nil {
		return nil
	}
	out := new(ObjectStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Redis) DeepCopyInto(out *Redis) {
	*out = *in
	out.Username = in.Username
	out.Password = in.Password
	out.Host = in.Host
	out.Port = in.Port
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Redis.
func (in *Redis) DeepCopy() *Redis {
	if in == nil {
		return nil
	}
	out := new(Redis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisSecrets) DeepCopyInto(out *RedisSecrets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisSecrets.
func (in *RedisSecrets) DeepCopy() *RedisSecrets {
	if in == nil {
		return nil
	}
	out := new(RedisSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMTP) DeepCopyInto(out *SMTP) {
	*out = *in
	out.Username = in.Username
	out.Password = in.Password
	out.FromAdress = in.FromAdress
	out.Domain = in.Domain
	out.Secure = in.Secure
	out.AuthType = in.AuthType
	out.Debug = in.Debug
	out.Host = in.Host
	out.Port = in.Port
	out.TemplateClass = in.TemplateClass
	out.PlainTextOnly = in.PlainTextOnly
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMTP.
func (in *SMTP) DeepCopy() *SMTP {
	if in == nil {
		return nil
	}
	out := new(SMTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Settings) DeepCopyInto(out *Settings) {
	*out = *in
	in.CreateOptions.DeepCopyInto(&out.CreateOptions)
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]settings.Source, len(*in))
		copy(*out, *in)
	}
	out.Database = in.Database
	out.SMTP = in.SMTP
	out.General = in.General
	out.ObjectStore = in.ObjectStore
	out.Redis = in.Redis
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Settings.
func (in *Settings) DeepCopy() *Settings {
	if in == nil {
		return nil
	}
	out := new(Settings)
	in.DeepCopyInto(out)
	return out
}
